### ISSUE TITLE
Operators in chars (and maybe strings)

### ISSUE THREAD

**Issue by amirkamil** [TheWolfA2/183lint#4]
For the following code, it results in a style error:
```
   } else if (slash1 != '/' || slash2 != '/' ||
```
Error message:
```
Incorrect spacing around / operator.
```

**Comment by TheWolfA2** [comment]
Figured this issue would resurface. I think a regex to clean the line of the contents of literal strings and characters should fix the issue :)

**Comment by amirkamil** [comment]
Has the fix been pushed to the live version? I'm still getting the same error.

**Comment by TheWolfA2** [comment]
Whoops! Just pulled and restarted the live version! Sorry about that!

**Comment by amirkamil** [comment]
No problem! Confirmed that it no longer flags that.
